apiVersion: v1
kind: ServiceAccount
metadata:
  name: certificate-signer
  namespace: kube-system
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: certificate-signer
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["certificatesigningrequests.certificates.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: certificate-signer
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: certificate-signer
subjects:
- kind: ServiceAccount
  name: certificate-signer
  namespace: kube-system