{{- with .Values.pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - {{ .accessModes }}
  resources:
    requests:
      storage: {{ .size }}
---
{{- end }}