apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  {{- range $key, $value := .Values.services }}
  - name: {{ $key }}
    port: {{ $value.port }}
    targetPort: {{ $value.port }}
    {{- if .options }}
{{ toYaml .options | indent 2 }}
    {{- end }}
  {{- end }}