apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  serviceName: {{ .Chart.Name }}
  replicas: {{ .Values.jenkins.replicas }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.jenkins.terminationGracePeriodSeconds }}
      serviceAccount: {{ .Values.jenkins.serviceAccount }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.jenkins.image.name }}.{{ .Values.jenkins.image.tag }}
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          ports:
          {{- range $key, $value := .Values.services }}
            - name: {{ $key }}
              containerPort: {{ $value.port }}
          {{- end }}
          volumeMounts:
            - name: {{ .Values.pvc.name }}
              mountPath: /var/jenkins_home
          resources:
{{ toYaml .Values.jenkins.resources | indent 12 }}
          livenessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 12
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.pvc.name }}
    spec:
      accessModes: [ {{ .Values.pvc.accessModes }} ]
      resources:
        requests:
          storage: {{ .Values.pvc.size }}
      storageClassName: {{ .Values.pvc.storageClassName }}